theme = "sphaero"

[keys.normal]
# S/O to https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
"0" = "goto_line_start"
"$" = "goto_line_end"
"G" = "goto_file_end"
g = { q = ":reflow" }
V = ["select_mode", "extend_to_line_bounds"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]

[editor]
gutters = ["diagnostics", "line-numbers", "spacer"]
auto-pairs = false

[editor.lsp]
auto-signature-help = false

